### ISSUE TITLE
Refactor Code for Modular File Structure

### ISSUE THREAD

**Issue by Mathious6** [Mathious6/gol-mathis_CDOF3#3]
Improve code maintainability and readability by refactoring the project structure. Currently, all logic is contained within a single 'main' file. The task involves separating the code into multiple files/modules, such as for grid creation, display functions, and the main game loop. This change aims to make the code base more organized and modular, facilitating easier updates and potential future expansions.

**Comment by Magnoir** [comment]
Salut, je pense pouvoir split ton code en plusieurs fichiers grid.py, calculation.py and display.py pour rendre ton code plus modulaire et séparer tes fonctions. Qu'est ce que tu en penses ?

**Comment by Mathious6** [comment]
> Salut, je pense pouvoir split ton code en plusieurs fichiers grid.py, calculation.py and display.py pour rendre ton code plus modulaire et séparer tes fonctions. Qu'est ce que tu en penses ?

Salut Magnoir, j'espère que tu vas bien! Yes c'est une super idée, c'est ce que je souhaitais faire mais je n'ai malheureusement pas le temps... N'hésite pas à faire une pull-request!

A+

**Comment by Mathious6** [comment]
Merci beaucoup pour ta contribution, à bientôt!
